### ISSUE TITLE
Behaviour packs is being not loaded.

### ISSUE THREAD

**Issue by ghost** [refteams/refAddonsManager#2]
I wanted to make a resource pack that changes the max stack size for the potions.  Loaded and nothing works.  It is also im not clear, does this plugin download and apply addons, or just make it available to download?

**Comment by alvin0319** [comment]
This plugin only sends resource pack and behavior pack and just loads them from the client. Nothing more then doing those things. The implementation of the PM-plugin-side is required in order to work your problem correctly.
